openapi: 3.0.3
info: {title: pmoves crush + notify + health (shim), version: 1.1.0}
servers: [{url: https://agent.example.com}]
paths:
  /crush:
    post:
      summary: Run pmoves 'crush' via portable pipx CLI
      operationId: runCrush
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command: {type: string, default: "crush"}
                args: {type: array, items: {type: string}, default: []}
                spec: {type: string, default: "pmoves==latest"}
                timeout: {type: integer, default: 900}
      responses: {"200": {description: Result stdout/stderr and exit code}}
  /notify/discord:
    post:
      summary: Discord notify
      operationId: notifyDiscord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                webhook_url: {type: string}
                content: {type: string, default: "Deploy completed ✅"}
                username: {type: string, default: "pmoves-agent"}
                embeds: {type: array, items: {type: object}}
      responses: {"200": {description: Status}}
  /notify/slack:
    post:
      summary: Slack notify
      operationId: notifySlack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bot_token: {type: string}
                channel: {type: string}
                text: {type: string, default: "Deploy completed ✅"}
                blocks: {type: array, items: {type: object}}
      responses: {"200": {description: Slack API response}}
  /notify/teams:
    post:
      summary: Teams notify
      operationId: notifyTeams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                webhook_url: {type: string}
                text: {type: string, default: "Deploy completed ✅"}
      responses: {"200": {description: Delivered}}
  /health/services:
    post:
      summary: Probe services
      operationId: healthServices
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                targets: {type: array, items: {type: object}}
                timeout: {type: integer, default: 8}
      responses: {"200": {description: Status list}}