openapi: 3.0.3
info: {title: PMOVES VL Sentinel, version: 1.0.0}
servers: [{url: https://agent.example.com}]
paths:
  /vl/guide:
    post:
      summary: Provide VL guidance based on images/logs/metrics
      operationId: vlGuide
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task: {type: string}
                images:
                  type: array
                  items:
                    type: object
                    properties: {url: {type: string}, b64: {type: string}}
                logs: {type: array, items: {type: string}}
                metrics: {type: object}
      responses: {"200": {description: Guidance text}}